### ISSUE TITLE
Missing license (so this is not open-source) and readme

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/go-verifcid#1]
The code in this repo has no explicit license, so it is not open-source code that anyone outside Protocol Labs can legally use. I know this is temporary, but we should still fix that ASAP (probably by following [the licensing policy](https://github.com/ipfs/community/blob/64d3c9b681ea85b6a4ce90e9ee248efe3b9338a7/docs/licensing-policy.md)).

This repo also really needs some kind of README. Again, I know it’s temporary, but our temporary stuff tends to stick around for a while and it would be very helpful to explain *at least* exactly why it’s temporary and what will happen to the content. (Is there anything to say about that other than *all of it* is going straight to go-cid? It seems small enough that the question “why did it need to go here temporarily in the first place instead of just landing in go-cid” would be a reasonable question.)

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant. This issue is no longer relevant, and therefore is being closed.
