### ISSUE TITLE
Add BLAKE3 to allowed list

### ISSUE THREAD

**Issue by markg85** [ipfs/go-verifcid#13]
Hi,

https://github.com/multiformats/go-multihash/issues/121#issuecomment-1016924547 added support for BLAKE3.
Currently this is technically available in go-ipfs 0.11.

However, because BLAKE3 isn't in the list of allowed hashes one gets `Error: potentially insecure hash functions not allowed`
That is with a IPFS command line like:
`ipfs add --nocopy --hash blake3 <somefile>`

Could BLAKE3 be allowed too?

Best regards,
Mark

**Comment by titusz** [comment]
See: https://github.com/ipfs/go-ipfs/issues/8650

**Comment by markg85** [comment]
> 

Awesome! Thank you for the pointer.
I'm not quite sure if this issue needs to be closed now..? It looks like it kinda depends on how it's going to be solved in ipfs/go-ipfs#8650 If a `--force` option would allow it then this issue would essentially be a non-issue.

**Comment by laudiacay** [comment]
Adding an upvote to this issue :) our project would love if IPFS/multihash supported blake3. Would make our infrastructure much easier to build.

**Comment by Jorropo** [comment]
Done in #16 !

**Comment by laudiacay** [comment]
!
